168 legal nav api updates
CCALI/a2jauthor pull request #177
Opened 2021-04-30 21:11 UTC by mikemitchel

Draft PR for comparing code

2021-05-03 00:06 UTC, mikemitchel commented on ckeditor/plugins/a2j-guid/dialogs/guid.js
> +            var selectedElement = dialog.getSelectedElement()
this is how the dialog grabs the source element that was double clicked

2021-05-03 00:07 UTC, mikemitchel commented on ckeditor/plugins/a2j-guid/dialogs/guid.js
> +                var sourceElement = selectedElement.getChild(0)
the 0th element is the legal-nav-resource-id and the 1 element is the span/wrapper that gives the little drag handle thing.

2021-05-03 08:14 UTC, AnubhavDhingra commented on ckeditor/plugins/a2j-guid/plugin.js
> +          element.setHtml(this.data.name)
This will reproduce the same error pointed out in #176

2021-05-03 13:45 UTC, AnubhavDhingra requested changes

2021-05-03 13:45 UTC, AnubhavDhingra commented on ckeditor/plugins/a2j-guid/plugin.js
> +          element.setHtml(this.data.name)
Could reproduce the same error pointed out in #176

2021-05-03 16:37 UTC, merged

2021-05-04 11:08 UTC, AnubhavDhingra commented
closes #168