WIP: update MAMP to single config.json
CCALI/a2jauthor pull request #213
Opened 2021-09-29 23:47 UTC by mikemitchel

working copy @chasenlehara for your review on setup

2021-10-06 15:24 UTC, chasenlehara requested changes

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
> +    - `cd ~/Sites/a2j/author && npm install`
`npm install` should probably be `npm ci` so the `package-lock.json` versions are used.

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
>  - MAMP
Maybe consider linking to `https://www.mamp.info/en/downloads/`?

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
> +- wkhtmltopdf used to generate assembled documents, download and install instructions https://wkhtmltopdf.org/downloads.html
I got this when I tried to open the `.pkg` installer:

<img width="372" alt="Screen Shot 2021-10-05 at 9 55 20 PM" src="https://user-images.githubusercontent.com/10070176/136142992-fb427787-6261-4782-acd4-a813cf8021ff.png">

It might be useful to link to `https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac` for an explanation on how to work around this.

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
> +4. Iinstall dependencies for Author:
Iinstall -> Install

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
> +    - `mysql> source ~/Sites/a2j/app/wiki/resources/caja_default_2018-10-09.sql`
This points to `Sites/a2j/app/wiki` but following the earlier instructions, I think this should be `Sites/a2j/app/author`.

Also, there’s a newer `caja_default_2021-03-23.sql`, should that be used instead?

One more thing: I think these sql files only modify the tables, but they don’t create the initial database. Can you confirm / what are the instructions for creating the database?

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
> +        "GUIDES_URL": "/a2j/userfiles/",
It looks like this is the same as [https://github.com/CCALI/a2jauthor/blob/develop/wiki/resources/config.json.sample](https://github.com/CCALI/a2jauthor/blob/develop/wiki/resources/config.json.sample), I wonder if the instructions should be to duplicate that and replace the necessary values?

2021-10-06 15:24 UTC, chasenlehara commented on wiki/Dev Environment MAMP.md
> +You should now be able to access the development app at [http://localhost/CALI/app/js/author](http://localhost/CALI/app/js/author). This will serve pre-dist assets and will reflect client-side change
Is `http://localhost/CALI/app/js/author` correct? It doesn’t seem to match up with the rest of the instructions.

2021-10-07 18:14 UTC, mitch-mitchel commented on wiki/Dev Environment MAMP.md
> +- wkhtmltopdf used to generate assembled documents, download and install instructions https://wkhtmltopdf.org/downloads.html
added

2021-10-07 19:30 UTC, mitch-mitchel commented on wiki/Dev Environment MAMP.md
> +You should now be able to access the development app at [http://localhost/CALI/app/js/author](http://localhost/CALI/app/js/author). This will serve pre-dist assets and will reflect client-side change
update it to `http://localhost/a2j/author`

2023-02-09 21:37 UTC, mikemitchel commented
this was covered by an updated PR https://github.com/CCALI/a2jauthor/pull/374

2023-02-09 21:37 UTC, closed without merging